name: Nightly CI for Bleeding Edge

on:
  schedule:
    # Nightly build at 2:42 A.M.
    - cron: "42 2 */1 * *"
  push:

jobs:
  nightly_ci:
    name: Python 3.10 on bleeding edge
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install OS dependencies
      run: |
        sudo apt-get update -yy
        sudo apt-get install -yy libsamplerate0 libsndfile1

    - name: Install Python dependencies
      run: |
        python -m pip install --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy scikit-learn matplotlib

    - name: Install librosa
      run: python -m pip install --upgrade-strategy only-if-needed -e .[test]

    - name: Run pytest
      run: pytest
